### PR TITLE
Remove Hawkular documentation

### PR DESCRIPTION
**Pull request by israel-hdez**

### CODE REVIEW

**Comment by israel-hdez** [comment]
ping @abonas

**Comment by abonas** [comment]
LGTM

**Comment by abonas** [comment]
@JPrause

**Comment by JPrause** [comment]
@Fryguy for your review

**Comment by abonas** [comment]
ping

**Comment by JPrause** [comment]
@martinpovolny @himdel can one of you review and merge.

**Comment by himdel** [comment]
Looks like it does remove all hawkular references from guides :+1:.

That said, `hawkular-dev-guide.adoc` is not really about hawkular, it seems to be a nice intro to manageiq with all the important concepts - a shame it wasn't linked from README, this could be useful for other teams.

So.. can we remove all files except that one, add that one to the menu, and if necessary clean it of hawkular-specific references?

**Comment by israel-hdez** [comment]
I can see the point, but I think `hawkular-dev-guide.adoc` file was accidentally placed in the guides. Looks like it was always unreachable (can't find a link to it). Moreover, it's written in ASCII-DOC while the rest of the guides is Markdown. Most likely that file was never being compiled to HTML.

If you think the content has value, I can for sure convert it to Markdown for proper compilation and place a link in README file. The content may require some review because some parts of it seem outdated (although most of it is still valid).

**Comment by himdel** [comment]
@israel-hdez Sounds good :) 

Should we merge this and add it back converted in a second PR or..?

**Comment by israel-hdez** [comment]
@himdel It's now converted to Markdown, properly linked from README, and all references to anything related to Hawkular/Middleware are removed.

**Comment by himdel** [comment]
Thanks @israel-hdez , LGTM, merging :)

**Pull request merged**
