### PR TITLE
Update rules to work with Rubocop 0.69.

### PR DESCRIPTION
**Pull request by martinpovolny**
Update rules to work with Rubocop 0.69.0.

Replacement for 
https://github.com/ManageIQ/guides/pull/343

### CODE REVIEW

**Comment by djberg96** [comment]
@martinpovolny Can you please update .rubocop_base.yml as part of this PR so that it adds:

`require: rubocop-performance`

**Comment by agrare** [comment]
@bdunne @martinpovolny we started seeing this shortly after this was merged: https://github.com/ManageIQ/topological_inventory-core/pull/131#issuecomment-492707505
```
Linter/Rubocop - Linter::Rubocop STDERR:
.rubocop-https---raw-githubusercontent-com-ManageIQ-guides-master--rubocop-base-yml: Layout/DefEndAlignment has the wrong namespace - should be Lint
.rubocop-https---raw-githubusercontent-com-ManageIQ-guides-master--rubocop-base-yml: Layout/EndAlignment has the wrong namespace - should be Lint
Warning: unrecognized cop Style/TrailingCommaInArrayLiteral found in .rubocop-https---raw-githubusercontent-com-ManageIQ-guides-master--rubocop-base-yml
Warning: unrecognized cop Style/TrailingCommaInHashLiteral found in .rubocop-https---raw-githubusercontent-com-ManageIQ-guides-master--rubocop-base-yml
Warning: unrecognized cop Style/TrailingCommaInArrayLiteral found in .rubocop.yml
Warning: unrecognized cop Style/TrailingCommaInHashLiteral found in .rubocop.yml
```

Do we need to bump rubocop version on miq-bot?

**Comment by djberg96** [comment]
@agrare Should be bumped now. I would think those only show up if 0.52 was run.

I didn't expect this to get merged until because now we'll get warnings about performance cops. Oh well, I'll submit a small PR soon.

**Comment by bdunne** [comment]
Sorry, should be fixed now.  Let me know if you see any more.

**Pull request merged**
