### PR TITLE
New hawkular dev guide

### PR DESCRIPTION
**Pull request by Jiri-Kremser**
I was trying to describe how to extend the middleware provider for other people from the middleware and our team. The original document is here https://github.com/hawkular/hawkular-docs/blob/master/mw_manager_developer_guide/topics/mw_provider.adoc

Also I am renaming the old one to `hawkular-hawkinit.md` (because it's 95% about hawkinit tool) and fixing some typos in it.

@blomquisg could you pls look? You asked me a month or two ago to add this also to this repo, so here it is.

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
cc @abonas @cfcosta

**Comment by martinpovolny** [comment]
ping @abonas, @cfcosta: can we merge this?

**Comment by cfcosta** [comment]
@jstickler hey, this is the documentation piece I talked with you about, we need some review on it so that other Java guys get more comfortable with Ruby more easily, can you (or someone else) help us?

**Comment by Jiri-Kremser** [comment]
(The target audience here is not any user/customer, but the devs)

**Pull request merged**
