### PR TITLE
Updated openstack infra guide

### PR DESCRIPTION
**Pull request by tzumainn**
updated features, added configuration steps for host fleecing and autoscaling

### CODE REVIEW

**Comment by blomquisg** [comment]
:+1: 

@Fryguy, @mfeifer any comments?

**Comment by Fryguy** [comment]
It seems that the zip file contains an automate script.  If that's the case, I feel like this should be in the [depot](http://manageiq.org/depot), and then the instructions here could just reference that entry in the depot (or perhaps all of some of the instructions should live in the depot entry).

cc @johnmark @chessbyte Thoughts?

**Comment by tzumainn** [comment]
@Fryguy @blomquisg  While we wait for an answer - would it be possible to merge this guide for now and potentially iterate later?  My hope is for this to land prior to OpenStack summit this coming week, so that there's documentation that matches what will be demoed there.

**Comment by johnmark** [comment]
+1 on adding to the depot - it's not too difficult to add as is. Let me know if you need help.

**Comment by tzumainn** [comment]
@johnmark That seems sensible; however, I don't think I'll have time to sort through the process this week, as I'm at the Summit right now.  Is it possible to commit this as is, and iterate later?  I think it'd be useful to have up-to-date documentation regarding the Summit demo.

**Comment by tzumainn** [comment]
@johnmark 

I've created a pull request to add the auto-scale files to the depot:

https://github.com/ManageIQ/manageiq_depot/pull/13

I'll update this pull request once the depot PR is reviewed and eventually merged.

Thanks!

**Comment by tzumainn** [comment]
@johnmark Thanks for merging the depot PR!  I've updated this one to reference the depot.

**Comment by tzumainn** [comment]
@johnmark @Fryguy @blomquisg any chance of a re-review of this?

**Comment by johnmark** [comment]
This looks good. I'm +1.

**Pull request merged**
