### PR TITLE
containers.md: Add openshift installation link

### PR DESCRIPTION
**Pull request by moolitayer**
CC @kbrock @NickLaMuro @enoodle

### CODE REVIEW

**Comment by NickLaMuro** [comment]
^ @hayesr There something we can do to add to this?

**Comment by hayesr** [comment]
@NickLaMuro Currently to get it to show on the website you need to make an addition here as well: https://github.com/ManageIQ/manageiq.org/blob/master/site/_data/menus/guides_menu.yml

**Comment by NickLaMuro** [comment]
@hayesr Cool, thanks!  I will make a PR for that shortly.

**Comment by NickLaMuro** [comment]
Well... so much for "I will make a PR for that shortly..."

Anyway, PR is here:  https://github.com/ManageIQ/manageiq.org/pull/524

**Pull request merged**
