### PR TITLE
Add missing dependencies to developer_setup for the noi4r gem

### PR DESCRIPTION
**Pull request by elad661**
**Description**

While setting up my environment, I encountered an error building the noi4r gem. To fix this, I needed to install this package group.

### CODE REVIEW

**Comment by elad661** [comment]
@Fryguy @romanblanco @simon3z @cben please review.

**Comment by cben** [comment]
:+1: Keep those guides PRs coming!  Most of us are already set up and can't catch those...

**Comment by romanblanco** [comment]
@elad661 LGTM, maybe just realign other comments

**Comment by elad661** [comment]
here it is again, this time with the comments properly aligned. thanks!

**Pull request merged**
