### PR TITLE
[WIP] Style/TrailingCommaInLiteral no longer exists

### PR DESCRIPTION
**Pull request by juliancheal**
Was split into Style/TrailingCommaInArrayLiteral and
Style/TrailingCommaInHashLiteral in 0.53.0

### CODE REVIEW

**Comment by Fryguy** [comment]
This has to coincide with a rubocop upgrade on the bot otherwise the bot will break.

**Comment by juliancheal** [comment]
@Fryguy yeah, just did it while I remembered, as @jrafanie and I had to changed it locally in our Rails 5.X upgrades.

**Comment by Fryguy** [comment]
I made a label to start tracking these types of requests :smile:

**Comment by bdunne** [comment]
It looks like this is resolved by https://github.com/ManageIQ/guides/pull/351

**Pull request closed without merging**
