### PR TITLE
Adds yarn install instructions for Fedora / CentOS

### PR DESCRIPTION
**Pull request by petrblaho**
I think that this was missing.

### CODE REVIEW

**Comment by himdel** [comment]
Thanks, these were previously only mentioned in the Debian/Ubuntu section, should be here as well.

**Comment by mtho11** [comment]
The recommended `yarn` install is natively and not through npm: https://yarnpkg.com/lang/en/docs/install/

**Comment by petrblaho** [comment]
@mtho11 this is interesting... perhaps we need issue for this b/c that covers not only Fedora / CentOS but other systems as well. What do you think, @himdel ?

**Comment by himdel** [comment]
Well.. it definitely makes sense to link to those instructions .. and I notice `yarn` is still missing from the mac section.

OTOH I'd keep the `npm install -g yarn` there as well, simply because these instructions should be complete by themselves, without having to recursively read other instructions, and the npm way is simpler than add a key, add a repo, and install.

**Comment by petrblaho** [comment]
@himdel ok. I will do that.

Is that fine with you, @mtho11 ?

**Comment by mtho11** [comment]
Perfect!

**Pull request merged**
