### PR TITLE
Add ManageIQ Bot info to developer_setup.md

### PR DESCRIPTION
**Pull request by mengxiwuu**
add ManageIQ Bot info in developer_set.md Further Reading section

### CODE REVIEW

**Comment by mengxiwuu** [comment]
@miq-bot add_labels enhancement

**Review by Fryguy — APPROVED** [review]

**Comment by mengxiwuu** [comment]
@miq-bot add-label enhancement

**Comment by mengxiwuu** [comment]
@miq-bot add_labels enhancement

**Comment by chessbyte** [comment]
Thank you @mengxiwuu for your first ManageIQ contribution!

**Pull request merged**
