### PR TITLE
Added RubyMine setup instructions

### PR DESCRIPTION
**Pull request by h-kataria**
@dclarizio @fryguy please review/merge

### CODE REVIEW

**Comment by dclarizio** [comment]
This looks good to me.  @Fryguy please verify that the images are placed and coded properly.

**Comment by kbrock** [comment]
Looks good

you can see the finished product [here](https://github.com/ManageIQ/guides/blob/ruby_mine_setup/developer_setup/ruby_mine_setup.md)

ASIDE: I had expected to see that branch at `h-katarina/ruby_mine_setup` and not `ManageIQ/ruby_mine_setup`

**Comment by h-kataria** [comment]
@kbrock i am not sure why the branch i pushed up shows the way it is, i checked out guides repo and followed same steps as i do for upstream/master repo.

**Comment by kbrock** [comment]
@h-kataria ok, I'm going to delete this on master

If you git `remote -v`, your `origin` is probably `ManageIQ` and not `h-katarina`.

**Pull request merged**
