### PR TITLE
Update rubocop config files from ManageIQ/manageiq

### PR DESCRIPTION
**Pull request by bdunne**

### CODE REVIEW

**Comment by bdunne** [comment]
@Fryguy @jrafanie Please review

**Comment by jrafanie** [comment]
LGTM, should we merge this first, then rebase the others to make sure they work as expected?

**Comment by bdunne** [comment]
@jrafanie Once this is merged, I'll remove the WIP's and rebase

**Comment by jrafanie** [comment]
I think all of the changes are because I re-organized the main repos rubocopy.yml and those changes never came back to guides.  I'm good with this, @Fryguy please merge if you 👍

**Pull request merged**
